apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location /api/transactions {
          proxy_pass http://transactions:4000/transactions;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
        location /banking/ {
          proxy_pass http://backend:5090/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
        location / {
          proxy_pass http://studentportfolio:80/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
      }
    }
